### ISSUE TITLE
Cities with several postal codes are not loaded properly

### ISSUE THREAD

**Issue by gelhaimer** [Lyssal/geographie-bundle#4]
Following cities are linked to several postal code in the same row.

**PARIS** - 75001-75002-75003-75004-75005-75006-75007-75008-75009-75010-75011-75012-75013-75014-75015-75016-75017-75018-75019-75020-75116
**MARSEILLE** - 13001-13002-13003-13004-13005-13006-13007-13008-13009-13010-13011-13012-13013-13014-13015-13016
**LYON** - 69001-69002-69003-69004-69005-69006-69007-69008-69009
**TOULOUSE** - 31000-31100-31200-31300-31400-31500
**NICE** - 06000-06100-06200-06300
**NANTES** - 44000-44100-44200-44300
**STRASBOURG** - 67000-67100-67200
**MONTPELLIER** - 34000-34070-34080-34090
**BORDEAUX** - 33000-33100-33200-33300-33800
**LILLE** - 59000-59160-59260-59777-59800

For instance, when a search is made on Paris, only one row will be returned. Nothing wrong at the moment. But as soon as a postal code search is made, there is no way to find 75009 which is also a valid postal code.

Since the `ville_code_postale` field is a string with a max length of 5, the actual value is truncated. 

As a work around, I made one row per postal code, which allows to find a city by its postal code without any trouble.

Another possibility would have been to make `ville_code_postale` attribute a longer string. However, it would make the search with "start with" clause less efficient.

I'll propose you my up to date files as a pull request.

**Comment by Lyssal** [comment]
Thank you again but I can't modify CSV files because they come from sql.sh and I will be able to replace them in the future.
And with this solution, we have many occurencies for one city (and if we search a city, we can't use GROUP BY ville_nom because many French cities have an identical name).

An other solution would be to create a new data table `code_postal` (ville_id, code VARCHAR(5), description TEXT NULLABLE).
For example we will have : 
`Paris ID, 75001, '1er arrondissement'`
etc

**Comment by gelhaimer** [comment]
This involve changing the way cities are created (splitting over - and create as much as postal code as needed). 

I don't really have the time to change that. Would you mind solving it ?

**Comment by Lyssal** [comment]
Yes, you can use the last release. I have created a `CodePostal` entity.

**Comment by Gregoriz** [comment]
It seems that the release broke the project up.

Since then, I got the following error while trying to update:

ClassNotFoundException in CodePostalAdmin.php line 16:
Attempted to load class "Admin" from namespace "Sonata\AdminBundle\Admin".
Did you forget a "use" statement for another namespace?

SonataAdmin is installed. Strange thing is CodePostalAdmin does not exist.

**Comment by gelhaimer** [comment]
It seems to work fine. I close the issue.
